# Generated by Django 5.2.11 on 2026-02-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studygroup_subject_user_is_approved_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['study_group', 'name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.studygroup', verbose_name='Study Group'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Subject Code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Subject Name'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'study_group')},
        ),
    ]
