# Generated by Django 5.2.11 on 2026-02-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='target_groups',
        ),
    ]
